[project]
name = "05"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.119.1",
    "pandas>=2.3.3",
    "scikit-learn==1.6.1",
    "uvicorn>=0.38.0",
]
